/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    'Api': {
      'name': string
      'type': 'sst.aws.Function'
      'url': string
    };
    'AuthSecret': {
      'type': 'sst.sst.Secret'
      'value': string
    };
    'Bucket': {
      'name': string
      'type': 'sst.aws.Bucket'
    };
    'Database': {
      'database': string
      'host': string
      'password': string
      'port': number
      'type': 'sst.aws.Postgres'
      'username': string
    };
    'Router': {
      'type': 'sst.aws.Router'
      'url': string
    };
    'Vpc': {
      'type': 'sst.aws.Vpc'
    };
    'Web': {
      'type': 'sst.aws.Nextjs'
      'url': string
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';

export {};
